2025-01-05 14:52:21,404 - DEBUG - run from json
2025-01-05 14:52:21,404 - DEBUG - [1736085141.4047222] starting run from json
2025-01-05 14:52:21,515 - DEBUG - process challenges w limit
2025-01-05 14:52:21,515 - DEBUG - [25d487eb] running root node with 5 attempts.
2025-01-05 14:52:21,515 - DEBUG - strarting attempt run
2025-01-05 14:52:21,716 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:21,716 - DEBUG - [25d8a9c8] running root node with 5 attempts.
2025-01-05 14:52:21,716 - DEBUG - strarting attempt run
2025-01-05 14:52:21,841 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:21,841 - DEBUG - [25ff71a9] running root node with 5 attempts.
2025-01-05 14:52:21,841 - DEBUG - strarting attempt run
2025-01-05 14:52:21,964 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:21,964 - DEBUG - [264363fd] running root node with 5 attempts.
2025-01-05 14:52:21,964 - DEBUG - strarting attempt run
2025-01-05 14:52:22,484 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:22,484 - DEBUG - [272f95fa] running root node with 5 attempts.
2025-01-05 14:52:22,484 - DEBUG - strarting attempt run
2025-01-05 14:52:22,685 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:22,685 - DEBUG - [27a28665] running root node with 5 attempts.
2025-01-05 14:52:22,685 - DEBUG - strarting attempt run
2025-01-05 14:52:22,800 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:22,800 - DEBUG - [28bf18c6] running root node with 5 attempts.
2025-01-05 14:52:22,800 - DEBUG - strarting attempt run
2025-01-05 14:52:22,928 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:22,928 - DEBUG - [28e73c20] running root node with 5 attempts.
2025-01-05 14:52:22,928 - DEBUG - strarting attempt run
2025-01-05 14:52:23,143 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:23,143 - DEBUG - [29623171] running root node with 5 attempts.
2025-01-05 14:52:23,143 - DEBUG - strarting attempt run
2025-01-05 14:52:23,317 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:23,318 - DEBUG - [29c11459] running root node with 5 attempts.
2025-01-05 14:52:23,318 - DEBUG - strarting attempt run
2025-01-05 14:52:23,454 - DEBUG - Error processing challenge: '(' was never closed (__init__.py, line 217)
2025-01-05 14:52:23,454 - DEBUG - Encountered 10 errors during processing
2025-01-05 14:52:23,456 - DEBUG - FINAL: took 2.05 secs to run 10 challenges
2025-01-05 14:52:23,456 - DEBUG - eval solutions
